version: '3.8'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_PORT: 3306
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_ONETIME_PASSWORD: 1
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql

    app:
        image: wp-project-skeleton
        restart: always
        build:
            context: .
        environment:
            DB_HOST: db
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/opt/wp-project-skeleton

volumes:
    db_data: