version: '3.8'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_PORT: 3306
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_ONETIME_PASSWORD: 1
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025

    app:
        image: wp-project-skeleton
        build:
            context: .
        environment:
            DB_HOST: db
        ports:
            - 80:80
        depends_on:
            - db
        volumes:
            - .:/opt/wp-project-skeleton

volumes:
    db_data: